#Leitura de chave inexistente
READ [key1]
#Criação e escrita de 3 chaves
WRITE [(key1,value1)(key2,value2)(key3,value3)]
#Leitura de chave existente
READ [key2]
#Escrita de uma chave nova e outra existente
WRITE [(key2,new-value2)(key4,value4)]
# backup 
BACKUP
# Eliminação de chave existente e de chave não existente
DELETE [key1,nonexistentKey]
#Espera de dois segundos
WAIT 2000
# Impressão de toda a tabela
SHOW